### ISSUE TITLE
How to Disable Hotspot and Enable wlan0 to accept available networks?

### ISSUE THREAD

**Issue by ak1801** [quangthanh010290/RPI3_HOTSPOTS#2]
Hi, 

I have followed the approach which you mentioned to create a hotspot on my RaspberryPi3. It works perfectly fine but I have  a requirement where sometimes I want to have to disable the Hotspot and connect to one of the available networks on wlan0 (wifi).
I cannot try Station mode because I do not know which all networks are available in a new premise.
So, I am actually stuck with hotspot now and cannot connect to internet from my pi. :(

I tried configuring wifi following instructions in the blog below, but got no luck!
http://weworkweplay.com/play/automatically-connect-a-raspberry-pi-to-a-wifi-network/

Is there any way I can achieve this. Any pointers will be appreciated.

Thanks in advance.

**Comment by quangthanh010290** [comment]
Do you know the SSID and password of your access point? make sure it use 2.4GHz  radio, and run
sudo sta your_ssid your_pass

**Comment by ak1801** [comment]
Yes I know the SSID and password of access point to which I am trying to connect. I tried that but It didn't work. 
It says - ifdown : interface wlan0 not configured

**Comment by quangthanh010290** [comment]
It's still running, interface wlan0 not configured mean wlan0 does not have ip address, so ifdown command takes no effect, it will try to reconnect in 3 minutes(you will see the ip address printed out, if not please restart and run sudo sta ... again.

**Comment by ak1801** [comment]
I tried it but getting the same result, even after restarting and running sudo sta command again. Getting same message - ifdown: interface wlan0 not configured. Attached screenshot of ifconfig after running sudo sta <ssid> <password> command.
![img_20170222_014227](https://cloud.githubusercontent.com/assets/6078058/23183053/af9a949a-f8a0-11e6-814f-4dfc6236dcb2.jpg)

Is any of the network interface setting/file corrupted? Is it possible to do a reset on wlan0?

**Comment by quangthanh010290** [comment]
did you success in connecting to the access point before?
please check the file: /etc/network/interface , it look like this:
source-directory /etc/network/interfaces.d
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet manual

allow-hotplug wlan0
iface wlan0 inet manual
    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf"
"

**Comment by quangthanh010290** [comment]
also check the file " /etc/wpa_supplicant/wpa_supplicant.conf "
it contains your ssid name and password.

**Comment by quangthanh010290** [comment]
if every thing is ok, run:
sudo ifdown wlan0
sudo ifup wlan0

**Comment by quangthanh010290** [comment]
what is you wifi security protocol?

**Comment by ak1801** [comment]
Yes, I was able to connect to access point before configuring the HotSpot. 

I rechecked the configurations, connected via LAN/eth0 and executed ./install and sta commands. (also I corrected the timezone and wifi zone to my country and time). My Wifi Security type is WPA-Personal and Encryption type is AES. Screenshots attached.

![img_20170223_005159](https://cloud.githubusercontent.com/assets/6078058/23228723/9cdd8da8-f963-11e6-9a65-c1cebe44b84e.jpg)
![img_20170223_005458](https://cloud.githubusercontent.com/assets/6078058/23228724/9ce21df0-f963-11e6-80f8-613dafa08e64.jpg)

This time it worked and the wlan0 got associated with the ssid which I passed as sta command argument. But, the IP address assigned is not correct. It is assigning a static ip address which I had configured earlier (long back). I am not able to figure out why is it picking static ip address? Is there any place, where this static ip needs to be flushed?  

![img_20170223_005552](https://cloud.githubusercontent.com/assets/6078058/23228725/9ce9cb2c-f963-11e6-929a-04012bc6e505.jpg)

**Comment by quangthanh010290** [comment]
sta command has flushed the ip "sudo ip addr flush dev wlan0", the ip was provied by the modem, i think you should take a look on your modem.

**Comment by quangthanh010290** [comment]
Can you ping google.com with this ip?

**Comment by ak1801** [comment]
I realized that I had configured a static ip for wlan0 in /etc/dhcpcd.conf file. After commenting it out, wlan0 got a dynamic ip address and everything got working perfectly fine. 
Thanks for your time and support.
