### ISSUE TITLE
How to turn back to normal internet

### ISSUE THREAD

**Issue by 20chix** [quangthanh010290/RPI3_HOTSPOTS#3]
Hi I runned your script and I would like to turn back and use normal wireless internet, how do I do it ?

**Comment by mashrurbd** [comment]
you cant

**Comment by quangthanh010290** [comment]
I recommend you run this script on console version, if you run on desktop version,  there are some new network services are installed and they changed the normal wireless internet. I will try to write a script to rollback to normal wireless .
