### ISSUE TITLE
Turn off hotspot

### ISSUE THREAD

**Issue by davidkowalk** [quangthanh010290/RPI3_HOTSPOTS#6]
The README manual does not explain how one can turn the hotspot off again (And I'm too stupid too understand the code). Currently I am just restarting my pi.

**Comment by quangthanh010290** [comment]
Hi David, you can run sudo sta to return to station mode, I had mentioned
on the Readme

Vào Th 6, 19 thg 10, 2018 lúc 01:37 David J. Kowalk <
notifications@github.com> đã viết:

**Comment by DapfiDuck** [comment]
Then I'm terribly sorry for overreading that twice. I hope I didn't cause
too much of an inconvenience.
